/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

import java.awt.event.ActionListener;

/**
 *
 * @author Dell
 */
public class Calculator extends javax.swing.JFrame {
    
    private double numarActual;
    private double rezultat;
    private int operatie;
    
    public void calculeaza() {
        switch (operatie) {
            case 1:
                rezultat = numarActual + Integer.parseInt(textAfisat.getText());
                break;
            case 2:
                rezultat = numarActual - Integer.parseInt(textAfisat.getText());
                break;
            case 3:
                rezultat = numarActual * Integer.parseInt(textAfisat.getText());
                break;
            case 4:
                rezultat = numarActual / Integer.parseInt(textAfisat.getText());
                break;
            case 5:
                String[] rezRadical = textAfisat.getText().split(" ");
                rezultat = Math.sqrt(Double.parseDouble(rezRadical[2]));
                
                break;
            case 6:
                String[] rezPutere = textAfisat.getText().split(" ");
                rezultat = Math.pow(numarActual, Double.parseDouble(rezPutere[3]));
                break;
            case 7:
                String[] rezFactorial = textAfisat.getText().split(" ");
                rezultat = 1;
                for (int i = 2; i <= Integer.parseInt(rezFactorial[0]); i++) {
                    rezultat *= i;
                }
            
        }
    }
    
    double batery = 50;
    StringBuffer sb = new StringBuffer();
    boolean aprins = false;
    
    Timer timer = new javax.swing.Timer(50, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (batery < 0.01) {
                blocheaza();                
                labelBaterie.setText("0");
                rosu.setVisible(false);
            } else if (batery > 0 && batery <= 100) {
                batery -= 0.1;
                bateryCheck(); 
                String procent = String.valueOf(batery);
                labelBaterie.setText(procent.substring(0, 4));
            }
            
           
        }
    });
    
    Timer timer2 = new javax.swing.Timer(50, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (batery >= 100) {
                batery = 100;
            } else {
                batery += 0.1;
                bateryCheck();
            }
            String procent = String.valueOf(batery);
            labelBaterie.setText(procent.substring(0, 4));
            
        }
    });
    
    public void bateryCheck() {
        if (batery > 75 && batery <= 100) {
            verde.setVisible(true);
            galben.setVisible(false);
            maro.setVisible(false);
            rosu.setVisible(false);
        } else if (batery > 50 && batery < 75) {
            verde.setVisible(false);
            galben.setVisible(true);
            maro.setVisible(false);
            rosu.setVisible(false);
        } else if (batery > 25 && batery < 50) {
            verde.setVisible(false);
            galben.setVisible(false);
            maro.setVisible(true);
            rosu.setVisible(false);
        } else if (batery > 0 && batery <= 25) {
            verde.setVisible(false);
            galben.setVisible(false);
            maro.setVisible(false);
            rosu.setVisible(true);
        }
    }
    
    public Calculator() {
        initComponents();
        textAfisat.setEditable(false);
        radioOff.setEnabled(false);
        lumina.setVisible(false);
        
        blocheaza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        textAfisat = new javax.swing.JTextField();
        radioOn = new javax.swing.JRadioButton();
        radioOff = new javax.swing.JRadioButton();
        bBack = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bPlus = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bPunct = new javax.swing.JButton();
        bEgal = new javax.swing.JButton();
        bImpartire = new javax.swing.JButton();
        bMinus = new javax.swing.JButton();
        bOri = new javax.swing.JButton();
        labelRosu = new javax.swing.JLabel();
        bRadical = new javax.swing.JButton();
        bPutere1 = new javax.swing.JButton();
        bFactorial = new javax.swing.JButton();
        bAprinde = new javax.swing.JRadioButton();
        bStinge = new javax.swing.JRadioButton();
        labelBaterie = new javax.swing.JLabel();
        labelBat = new javax.swing.JLabel();
        labelProcent = new javax.swing.JLabel();
        lampa = new javax.swing.JLabel();
        lumina = new javax.swing.JLabel();
        rosu = new javax.swing.JLabel();
        maro = new javax.swing.JLabel();
        galben = new javax.swing.JLabel();
        verde = new javax.swing.JLabel();
        backgroundNegru = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textAfisat.setBackground(new java.awt.Color(153, 153, 0));
        textAfisat.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textAfisat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textAfisat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAfisatActionPerformed(evt);
            }
        });
        getContentPane().add(textAfisat);
        textAfisat.setBounds(217, 66, 343, 47);

        buttonGroup1.add(radioOn);
        radioOn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        radioOn.setForeground(new java.awt.Color(255, 255, 255));
        radioOn.setText("ON");
        radioOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOnActionPerformed(evt);
            }
        });
        getContentPane().add(radioOn);
        radioOn.setBounds(250, 170, 40, 23);

        buttonGroup1.add(radioOff);
        radioOff.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        radioOff.setForeground(new java.awt.Color(255, 255, 255));
        radioOff.setText("OFF");
        radioOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOffActionPerformed(evt);
            }
        });
        getContentPane().add(radioOff);
        radioOff.setBounds(310, 170, 45, 23);

        bBack.setBackground(new java.awt.Color(153, 153, 0));
        bBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bBack.setText("<-");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack);
        bBack.setBounds(370, 160, 52, 49);

        bC.setBackground(new java.awt.Color(153, 153, 0));
        bC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bC.setText("C");
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });
        getContentPane().add(bC);
        bC.setBounds(440, 160, 52, 49);

        bPlus.setBackground(new java.awt.Color(153, 153, 0));
        bPlus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bPlus.setText("+");
        bPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlusActionPerformed(evt);
            }
        });
        getContentPane().add(bPlus);
        bPlus.setBounds(510, 160, 52, 49);

        b7.setBackground(new java.awt.Color(153, 153, 0));
        b7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(300, 235, 52, 49);

        b8.setBackground(new java.awt.Color(153, 153, 0));
        b8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(370, 235, 52, 49);

        b9.setBackground(new java.awt.Color(153, 153, 0));
        b9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(441, 235, 52, 49);

        b4.setBackground(new java.awt.Color(153, 153, 0));
        b4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(300, 300, 52, 49);

        b5.setBackground(new java.awt.Color(153, 153, 0));
        b5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(370, 300, 52, 49);

        b6.setBackground(new java.awt.Color(153, 153, 0));
        b6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(441, 300, 52, 49);

        b1.setBackground(new java.awt.Color(153, 153, 0));
        b1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(300, 369, 52, 49);

        b2.setBackground(new java.awt.Color(153, 153, 0));
        b2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(370, 369, 52, 49);

        b3.setBackground(new java.awt.Color(153, 153, 0));
        b3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(441, 369, 52, 49);

        b0.setBackground(new java.awt.Color(153, 153, 0));
        b0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(217, 439, 135, 49);

        bPunct.setBackground(new java.awt.Color(153, 153, 0));
        bPunct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bPunct.setText(".");
        bPunct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPunctActionPerformed(evt);
            }
        });
        getContentPane().add(bPunct);
        bPunct.setBounds(370, 439, 52, 49);

        bEgal.setBackground(new java.awt.Color(153, 153, 0));
        bEgal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bEgal.setText("=");
        bEgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEgalActionPerformed(evt);
            }
        });
        getContentPane().add(bEgal);
        bEgal.setBounds(441, 439, 122, 49);

        bImpartire.setBackground(new java.awt.Color(153, 153, 0));
        bImpartire.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bImpartire.setText("÷");
        bImpartire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImpartireActionPerformed(evt);
            }
        });
        getContentPane().add(bImpartire);
        bImpartire.setBounds(511, 369, 52, 49);

        bMinus.setBackground(new java.awt.Color(153, 153, 0));
        bMinus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bMinus.setText("-");
        bMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinusActionPerformed(evt);
            }
        });
        getContentPane().add(bMinus);
        bMinus.setBounds(511, 235, 52, 49);

        bOri.setBackground(new java.awt.Color(153, 153, 0));
        bOri.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOri.setText("×");
        bOri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOriActionPerformed(evt);
            }
        });
        getContentPane().add(bOri);
        bOri.setBounds(511, 302, 52, 49);

        labelRosu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelRosu.setForeground(new java.awt.Color(255, 0, 0));
        labelRosu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(labelRosu);
        labelRosu.setBounds(217, 21, 327, 27);

        bRadical.setBackground(new java.awt.Color(153, 153, 0));
        bRadical.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bRadical.setText("√");
        bRadical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRadicalActionPerformed(evt);
            }
        });
        getContentPane().add(bRadical);
        bRadical.setBounds(221, 235, 61, 49);

        bPutere1.setBackground(new java.awt.Color(153, 153, 0));
        bPutere1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bPutere1.setText("^");
        bPutere1.setToolTipText("Ridicare la putere");
        bPutere1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPutere1ActionPerformed(evt);
            }
        });
        getContentPane().add(bPutere1);
        bPutere1.setBounds(221, 300, 61, 49);

        bFactorial.setBackground(new java.awt.Color(153, 153, 0));
        bFactorial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bFactorial.setText("x!");
        bFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(bFactorial);
        bFactorial.setBounds(221, 367, 61, 54);

        buttonGroup2.add(bAprinde);
        bAprinde.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bAprinde.setForeground(new java.awt.Color(255, 255, 255));
        bAprinde.setText("Aprinde");
        bAprinde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAprindeActionPerformed(evt);
            }
        });
        getContentPane().add(bAprinde);
        bAprinde.setBounds(70, 410, 80, 27);

        buttonGroup2.add(bStinge);
        bStinge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bStinge.setForeground(new java.awt.Color(255, 255, 255));
        bStinge.setText("Stinge");
        bStinge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStingeActionPerformed(evt);
            }
        });
        getContentPane().add(bStinge);
        bStinge.setBounds(70, 450, 70, 27);

        labelBaterie.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelBaterie.setForeground(new java.awt.Color(255, 255, 255));
        labelBaterie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelBaterie.setText("50");
        getContentPane().add(labelBaterie);
        labelBaterie.setBounds(587, 103, 73, 24);

        labelBat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelBat.setForeground(new java.awt.Color(255, 255, 255));
        labelBat.setText("Baterie");
        getContentPane().add(labelBat);
        labelBat.setBounds(626, 66, 51, 19);

        labelProcent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelProcent.setForeground(new java.awt.Color(255, 255, 255));
        labelProcent.setText("%");
        getContentPane().add(labelProcent);
        labelProcent.setBounds(672, 103, 17, 24);

        lampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/Laaaaaampa.png"))); // NOI18N
        getContentPane().add(lampa);
        lampa.setBounds(20, 10, 150, 520);

        lumina.setForeground(new java.awt.Color(0, 0, 0));
        lumina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/g123.png"))); // NOI18N
        getContentPane().add(lumina);
        lumina.setBounds(0, 0, 730, 530);

        rosu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/rosu.png"))); // NOI18N
        getContentPane().add(rosu);
        rosu.setBounds(580, 160, 150, 260);

        maro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/maro.png"))); // NOI18N
        getContentPane().add(maro);
        maro.setBounds(580, 160, 150, 260);

        galben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/galben.png"))); // NOI18N
        getContentPane().add(galben);
        galben.setBounds(580, 160, 150, 260);

        verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/verde.png"))); // NOI18N
        getContentPane().add(verde);
        verde.setBounds(580, 160, 150, 260);

        backgroundNegru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/negru.png"))); // NOI18N
        getContentPane().add(backgroundNegru);
        backgroundNegru.setBounds(0, 0, 730, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAfisatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAfisatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAfisatActionPerformed
    
    private void blocheaza() {
        
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        bBack.setEnabled(false);
        bPlus.setEnabled(false);
        bMinus.setEnabled(false);
        bOri.setEnabled(false);
        bImpartire.setEnabled(false);
        bC.setEnabled(false);
        bPunct.setEnabled(false);
        bEgal.setEnabled(false);
        bRadical.setEnabled(false);
        bFactorial.setEnabled(false);
        bPutere1.setEnabled(false);
    }
    
    private void activeaza() {
        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        bBack.setEnabled(true);
        bPlus.setEnabled(true);
        bMinus.setEnabled(true);
        bOri.setEnabled(true);
        bImpartire.setEnabled(true);
        bC.setEnabled(true);
        bPunct.setEnabled(true);
        bEgal.setEnabled(true);
        bRadical.setEnabled(true);
        bFactorial.setEnabled(true);
        bPutere1.setEnabled(true);
    }
    

    private void radioOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOnActionPerformed
        timer.start();
        radioOn.setEnabled(false);
        radioOff.setEnabled(true);
        activeaza();
    }//GEN-LAST:event_radioOnActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        textAfisat.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bCActionPerformed

    private void bPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlusActionPerformed
        operatie = 1;
        numarActual = Double.parseDouble(textAfisat.getText());
        if (numarActual % 10 == 0) {
            String nr[] = textAfisat.getText().split(".");
            labelRosu.setText(nr[0] + "+");
        } else {
            labelRosu.setText(textAfisat.getText() + "+");
        }
        
        textAfisat.setText("");
    }//GEN-LAST:event_bPlusActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        textAfisat.setText(textAfisat.getText() + "8");
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        textAfisat.setText(textAfisat.getText() + "9");
    }//GEN-LAST:event_b9ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        textAfisat.setText(textAfisat.getText() + "5");
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        textAfisat.setText(textAfisat.getText() + "6");      // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        textAfisat.setText(textAfisat.getText() + "2");      // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        textAfisat.setText(textAfisat.getText() + "3");      // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void bPunctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPunctActionPerformed
        textAfisat.setText(textAfisat.getText() + ".");        // TODO add your handling code here:
    }//GEN-LAST:event_bPunctActionPerformed

    private void bEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEgalActionPerformed
        labelRosu.setText("");
        calculeaza();
        
        textAfisat.setText(String.valueOf(rezultat));
        if (String.valueOf(rezultat).equals("Infinity")) {
            textAfisat.setText("ERROR");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bEgalActionPerformed

    private void bImpartireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImpartireActionPerformed
        operatie = 4;
        numarActual = Double.parseDouble(textAfisat.getText());
        if (numarActual % 10 == 0) {
            String nr[] = textAfisat.getText().split(".");
            labelRosu.setText(nr[0] + "÷");
        } else {
            labelRosu.setText(textAfisat.getText() + "÷");
        }
        textAfisat.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bImpartireActionPerformed

    private void bMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinusActionPerformed
        operatie = 2;
        numarActual = Double.parseDouble(textAfisat.getText());
        if (numarActual % 10 == 0) {
            String nr[] = textAfisat.getText().split(".");
            labelRosu.setText(nr[0] + "-");
        } else {
            labelRosu.setText(textAfisat.getText() + "-");
        }
        textAfisat.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bMinusActionPerformed

    private void bOriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOriActionPerformed
        operatie = 3;
        numarActual = Double.parseDouble(textAfisat.getText());
        if (numarActual % 10 == 0) {
            String nr[] = textAfisat.getText().split(".");
            labelRosu.setText(nr[0] + "×");
        } else {
            labelRosu.setText(textAfisat.getText() + "×");
        }
        textAfisat.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bOriActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
        textAfisat.setText(textAfisat.getText() + "1");
    }//GEN-LAST:event_b1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        textAfisat.setText(textAfisat.getText() + "4");        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        textAfisat.setText(textAfisat.getText() + "7");        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        textAfisat.setText(textAfisat.getText() + "0");        // TODO add your handling code here:
    }//GEN-LAST:event_b0ActionPerformed

    private void radioOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOffActionPerformed
        timer.stop();
        radioOff.setEnabled(false);
        radioOn.setEnabled(true);
        textAfisat.setText("");
        operatie = 0;
        numarActual = 0;
        blocheaza();

    }//GEN-LAST:event_radioOffActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        String textActual = textAfisat.getText();
        String text = textActual.substring(0, textActual.length() - 1);
        textAfisat.setText(text);
    }//GEN-LAST:event_bBackActionPerformed

    private void bRadicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRadicalActionPerformed
        textAfisat.setText("Radical din ");
        operatie = 5;

    }//GEN-LAST:event_bRadicalActionPerformed

    private void bPutere1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPutere1ActionPerformed
        operatie = 6;
        numarActual = Double.parseDouble(textAfisat.getText());
        textAfisat.setText(textAfisat.getText() + " la puterea ");
    }//GEN-LAST:event_bPutere1ActionPerformed

    private void bFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFactorialActionPerformed
        operatie = 7;
        textAfisat.setText(textAfisat.getText() + " !");// TODO add your handling code here:
    }//GEN-LAST:event_bFactorialActionPerformed

    private void bAprindeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAprindeActionPerformed
        bateryCheck();
        timer2.start();
        aprins = true;
        lumina.setVisible(true);
        bAprinde.setEnabled(false);
        bStinge.setEnabled(true);
        radioOn.setForeground(Color.black);
        radioOff.setForeground(Color.black);
        bAprinde.setForeground(Color.black);
        bStinge.setForeground(Color.black);
        labelBat.setForeground(Color.black);
        labelBaterie.setForeground(Color.black);
        labelProcent.setForeground(Color.black);
        
        textAfisat.setBackground(Color.black);
        bBack.setBackground(Color.black);
        bC.setBackground(Color.black);
        bPlus.setBackground(Color.black);
        b1.setBackground(Color.black);
        b2.setBackground(Color.black);
        b3.setBackground(Color.black);
        b4.setBackground(Color.black);
        b5.setBackground(Color.black);
        b6.setBackground(Color.black);
        b7.setBackground(Color.black);
        b8.setBackground(Color.black);
        b9.setBackground(Color.black);
        b0.setBackground(Color.black);
        bPunct.setBackground(Color.black);
        bEgal.setBackground(Color.black);
        bImpartire.setBackground(Color.black);
        bMinus.setBackground(Color.black);
        bOri.setBackground(Color.black);
        bRadical.setBackground(Color.black);
        bPutere1.setBackground(Color.black);
        bFactorial.setBackground(Color.black);
        
        textAfisat.setForeground(Color.white);
        bBack.setForeground(Color.white);
        bC.setForeground(Color.white);
        bPlus.setForeground(Color.white);
        b1.setForeground(Color.white);
        b2.setForeground(Color.white);
        b3.setForeground(Color.white);
        b4.setForeground(Color.white);
        b5.setForeground(Color.white);
        b6.setForeground(Color.white);
        b7.setForeground(Color.white);
        b8.setForeground(Color.white);
        b9.setForeground(Color.white);
        b0.setForeground(Color.white);
        bPunct.setForeground(Color.white);
        bEgal.setForeground(Color.white);
        bImpartire.setForeground(Color.white);
        bMinus.setForeground(Color.white);
        bOri.setForeground(Color.white);
        bRadical.setForeground(Color.white);
        bPutere1.setForeground(Color.white);
        bFactorial.setForeground(Color.white);
    }//GEN-LAST:event_bAprindeActionPerformed

    private void bStingeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStingeActionPerformed
        radioOn.setForeground(Color.white);
        radioOff.setForeground(Color.white);
        bAprinde.setForeground(Color.white);
        bStinge.setForeground(Color.white);
        labelBat.setForeground(Color.white);
        labelBaterie.setForeground(Color.white);
        labelProcent.setForeground(Color.white);
        timer2.stop();
        aprins = false;
        lumina.setVisible(false);
        bAprinde.setEnabled(true);
        bStinge.setEnabled(false);
        
        textAfisat.setBackground(Color.white);
        bBack.setBackground(Color.white);
        bC.setBackground(Color.white);
        bPlus.setBackground(Color.white);
        b1.setBackground(Color.white);
        b2.setBackground(Color.white);
        b3.setBackground(Color.white);
        b4.setBackground(Color.white);
        b5.setBackground(Color.white);
        b6.setBackground(Color.white);
        b7.setBackground(Color.white);
        b8.setBackground(Color.white);
        b9.setBackground(Color.white);
        b0.setBackground(Color.white);
        bPunct.setBackground(Color.white);
        bEgal.setBackground(Color.white);
        bImpartire.setBackground(Color.white);
        bMinus.setBackground(Color.white);
        bOri.setBackground(Color.white);
        bRadical.setBackground(Color.white);
        bPutere1.setBackground(Color.white);
        bFactorial.setBackground(Color.white);
        
        textAfisat.setForeground(Color.black);
        bBack.setForeground(Color.black);
        bC.setForeground(Color.black);
        bPlus.setForeground(Color.black);
        b1.setForeground(Color.black);
        b2.setForeground(Color.black);
        b3.setForeground(Color.black);
        b4.setForeground(Color.black);
        b5.setForeground(Color.black);
        b6.setForeground(Color.black);
        b7.setForeground(Color.black);
        b8.setForeground(Color.black);
        b9.setForeground(Color.black);
        b0.setForeground(Color.black);
        bPunct.setForeground(Color.black);
        bEgal.setForeground(Color.black);
        bImpartire.setForeground(Color.black);
        bMinus.setForeground(Color.black);
        bOri.setForeground(Color.black);
        bRadical.setForeground(Color.black);
        bPutere1.setForeground(Color.black);
        bFactorial.setForeground(Color.black);
    }//GEN-LAST:event_bStingeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator c = new Calculator();
                c.setVisible(true);
                c.setDefaultCloseOperation(EXIT_ON_CLOSE);
                c.setSize(750, 570);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JRadioButton bAprinde;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bC;
    private javax.swing.JButton bEgal;
    private javax.swing.JButton bFactorial;
    private javax.swing.JButton bImpartire;
    private javax.swing.JButton bMinus;
    private javax.swing.JButton bOri;
    private javax.swing.JButton bPlus;
    private javax.swing.JButton bPunct;
    private javax.swing.JButton bPutere1;
    private javax.swing.JButton bRadical;
    private javax.swing.JRadioButton bStinge;
    private javax.swing.JLabel backgroundNegru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel galben;
    private javax.swing.JLabel labelBat;
    private javax.swing.JLabel labelBaterie;
    private javax.swing.JLabel labelProcent;
    private javax.swing.JLabel labelRosu;
    private javax.swing.JLabel lampa;
    private javax.swing.JLabel lumina;
    private javax.swing.JLabel maro;
    private javax.swing.JRadioButton radioOff;
    private javax.swing.JRadioButton radioOn;
    private javax.swing.JLabel rosu;
    private javax.swing.JTextField textAfisat;
    private javax.swing.JLabel verde;
    // End of variables declaration//GEN-END:variables
}
